language: ruby
sudo: false
cache: bundler
bundler_args: --retry=3 --jobs=3
before_script:
  - psql -c 'create database jobs_ruby_tw_test;' -U postgres
  - bin/setup
  - bin/rake db:test:prepare
rvm:
  - 2.3
matrix:
  fast_finish: true
addons:
  postgresql: 9.6
