language: ruby
sudo: false
cache: bundler
bundler_args: --retry=3 --jobs=3
before_script:
  - bin/setup
  - bin/rake db:test:prepare
rvm:
  - 2.3
  - 2.5
  - ruby-head
matrix:
  allow_failures:
    - rvm: 2.0
    - rvm: ruby-head
  fast_finish: true
